name: Push Validations

on:
  push:
    branches: [master, dev, feature/*, bugfix/*, chore/*]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12.x]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version${{ matrix.node_version}}

      - name: install
        run: npm ci

`     - name: run lint
        npm run lint:ci instead

      - name: run test
        run: npm test

      - name: run build
        run: npm run build



